# Temporary Makefile for library toflib. Generation date = Mon Sep 22 07:50:16 CEST 2003
include /home/pcl2483/pedro/jadesoft/GNUmake-rules
#
/home/pcl2483/pedro/jadesoft/lib/libtoflib.a : /home/pcl2483/pedro/jadesoft/lib/libtoflib.a( tofint.o tofcor.o tofmas.o tfctd1.o tofbra.o tfstor.o tofard.o rd0880.o tofin2.o cmass.o tfarnw.o tofsmp.o corcst.o tofsm2.o tofsm3.o tofar2.o tofma2.o atofun.o tofcl2.o tofclc.o atofrw.o atfugr.o mocard.o agrpr.o )
#
/home/pcl2483/pedro/jadesoft/lib/libtoflib.a( tofint.o tofmas.o tofsmp.o atofun.o ) :	 chead.for
/home/pcl2483/pedro/jadesoft/lib/libtoflib.a( tofint.o tofmas.o tfctd1.o tofard.o tofin2.o tofar2.o atofun.o mocard.o ) :	 ddata.for
/home/pcl2483/pedro/jadesoft/lib/libtoflib.a( tofmas.o ) :	 tcalcm1.for
/home/pcl2483/pedro/jadesoft/lib/libtoflib.a( tofmas.o tofard.o rd0880.o tfarnw.o tofsmp.o tofsm3.o ) :	 tfadc.for
/home/pcl2483/pedro/jadesoft/lib/libtoflib.a( tofmas.o tofard.o rd0880.o tfarnw.o tofsmp.o tofsm3.o tofclc.o ) :	 tfprm.for
