# Temporary Makefile for library jademus. Generation date = Mon Sep 22 07:44:41 CEST 2003
include /home/pcl2483/pedro/jadesoft/GNUmake-rules
#
/home/pcl2483/pedro/jadesoft/lib/libjademus.a : /home/pcl2483/pedro/jadesoft/lib/libjademus.a( muini.o muana.o mufini.o mucon.o mureg.o muanab.o muanac.o mucuts.o mumess.o muerry.o mucoor.o mudump.o mufsta.o mu2pul.o tanthm.o muconw.o muanaf.o muffle.o muregm.o muregy.o musafe.o muregs.o mudchk.o mufflb.o muffls.o mufflr.o mufflt.o mufflz.o muffly.o mufflx.o muendp.o mufmat.o muloch.o mupic.o xymud.o muhit.o muhits.o muhdsp.o muwire.o muons.o )
#
/home/pcl2483/pedro/jadesoft/lib/libjademus.a( mureg.o ) :	 cadmin.for
/home/pcl2483/pedro/jadesoft/lib/libjademus.a( mupic.o xymud.o muhdsp.o ) :	 cgraph.for
/home/pcl2483/pedro/jadesoft/lib/libjademus.a( muregy.o ) :	 cmtemp.for
/home/pcl2483/pedro/jadesoft/lib/libjademus.a( muini.o ) :	 cmuanp.for
/home/pcl2483/pedro/jadesoft/lib/libjademus.a( mucon.o mureg.o muanab.o muanac.o mucuts.o mucoor.o mudump.o muconw.o muanaf.o mupic.o muhit.o muhits.o muhdsp.o muons.o ) :	 cmubcs.for
/home/pcl2483/pedro/jadesoft/lib/libjademus.a( mucon.o mureg.o muanac.o mucoor.o mufsta.o tanthm.o muconw.o muanaf.o muffle.o mufflt.o mufflz.o muffly.o muendp.o muloch.o mupic.o muwire.o ) :	 cmucalib.for
/home/pcl2483/pedro/jadesoft/lib/libjademus.a( muconw.o ) :	 cmued.for
/home/pcl2483/pedro/jadesoft/lib/libjademus.a( muconw.o ) :	 cmuedwrk.for
/home/pcl2483/pedro/jadesoft/lib/libjademus.a( muanaf.o muffle.o mufflb.o muffls.o mufflt.o mufflz.o muffly.o muendp.o ) :	 cmuffl.for
/home/pcl2483/pedro/jadesoft/lib/libjademus.a( muanaf.o muffle.o mudchk.o mufflb.o muffls.o mufflr.o mufflt.o mufflz.o muffly.o mufflx.o muendp.o mufmat.o muloch.o ) :	 cmufwork.for
/home/pcl2483/pedro/jadesoft/lib/libjademus.a( mureg.o muanaf.o muffle.o muregy.o mufflt.o mufflz.o muffly.o muendp.o muloch.o ) :	 cmureg.for
/home/pcl2483/pedro/jadesoft/lib/libjademus.a( muini.o mufini.o mucuts.o mucoor.o muanaf.o ) :	 cmustat.for
