# Temporary Makefile for library boslib. Generation date = Tue Oct 25 13:26:41 CEST 2016
include /home/andriish/Projects/JADE.git/trunk/jadesoft/GNUmake-rules
#
/home/andriish/Projects/JADE.git/trunk/jadesoft/lib/libboslib.a : /home/andriish/Projects/JADE.git/trunk/jadesoft/lib/libboslib.a( bint.o ibln.o brnm.o bcre.o ccre.o bloc.o cloc.o bchm.o bdar.o bpos.o bnxt.o cnxt.o bmlt.o bsaw.o bdls.o bdlm.o bdlg.o bgar.o bdmp.o bsta.o bchl.o cchl.o bgac.o bsls.o indar.o breadc.o readhl.o bread.o cread.o bwrite.o brds.o bwrs.o bfrd.o binp.o boutp.o bseq.o rdvar.o msgpr.o blocda.o binlda.o bloada.o poda.o dada.o rdda.o bpasda.o itoda.o uwp.o asrd.o uhist.o defst.o vall.o sort4.o ptext1.o pall.o pcond.o pstor.o ptabl.o phist.o pcorr.o histpr.o ccor.o pvert.o bfmt.o iaf.o vecsub.o ucorr.o )
#
/home/andriish/Projects/JADE.git/trunk/jadesoft/lib/libboslib.a( bint.o ibln.o brnm.o bcre.o ccre.o bloc.o cloc.o bchm.o bdar.o bpos.o bnxt.o cnxt.o bmlt.o bsaw.o bdls.o bdlm.o bdlg.o bgar.o bdmp.o bsta.o bchl.o cchl.o bsls.o indar.o brds.o bwrs.o binp.o boutp.o bseq.o ) :\t acs.for
/home/andriish/Projects/JADE.git/trunk/jadesoft/lib/libboslib.a( bint.o bdmp.o blocda.o binlda.o bloada.o poda.o dada.o rdda.o bpasda.o ) :\t ccs.for
/home/andriish/Projects/JADE.git/trunk/jadesoft/lib/libboslib.a( brnm.o bcre.o ccre.o bchm.o bdls.o binp.o ) :\t star.for
