C   29/01/79 202121516  MEMBER NAME  LGCCTK   (SOURCE)      FORTRAN
      SUBROUTINE LGCCTK(IERT)
C
C     S.YAMADA      28-09-78  22:35
C     LAST MODIFICATION   29-01-79  10:35
C     LAST MODIFICATION   01-11-79  23:10   S.KOMAMIYA
C     LAST MODIFICATION   09-11-79  18:30   S.KOMAMIYA
C               CHANGED THE SUBROUTINE NAME  LGCCTL-->LGCCT1
C               CHANGED THE SUBROUTINE NAME  LGCLUS-->LGCLS1
C
C     CONTROL SUBROUTINE FOR LGCLUS
C     THIS IS CREATED TO FIND CLUSTERS IN THE THREE PARTS SEPARATELY.
C
      IMPLICIT INTEGER *2 (H)
C
#include "clgwork1.for"
C
C---- NCLST = NO.OF THE LOCATED CLUSTERS.
C---- MAPCL(J)=THE INDEX OF THE FIRST MEMBER OF THE J-TH CLUSTER
C               IN THE HLGADC.
C
      COMMON/ CLGVRN/ NVRSN(20)
      DATA NVCODE/279012910/
      NVRSN(6) = NVCODE
C
      IF(LNG.LE.2) GO TO 101
C
C---- CLUSTER FINDING IS REPEATED FOR EACH PART
   10   DO 20 JP=1,3
        NHIT = (HPOINT(JP+1)-HPOINT(JP))/2
        INIT = (HPOINT(JP)+1)/2
        CALL LGCLSK(JP,INIT,NHIT,IER)
        IERT = IERT+IER
   20   CONTINUE
C---- SET NO. OF CLUSTERS IN EACH PART.
      NCLBEC(3) = NCLBEC(3)-NCLBEC(2)
      NCLBEC(2) = NCLBEC(2)-NCLBEC(1)
  100 RETURN
C
  101 MAPCL(1) = 1
      RETURN
      END
