# Temporary Makefile for library vertex. Generation date = Mon Sep 22 07:44:11 CEST 2003
include /home/pcl2483/pedro/jadesoft/GNUmake-rules
#
/home/pcl2483/pedro/jadesoft/lib/libvertex.a : /home/pcl2483/pedro/jadesoft/lib/libvertex.a( vtxini.o vtxbnk.o vtxaft.o vtxpre.o vtxpnt.o vtxsrc.o vtxee.o vertex.o )
#
/home/pcl2483/pedro/jadesoft/lib/libvertex.a( vtxbnk.o vtxpre.o ) :	 cdata.for
