FROM fedora:39
RUN         yum -y install dnf-plugins-core && \
RUN         yum -y install rpm-build && \
            yum -y install bc make ninja-build cmake binutils git wget diffutils file sed gawk grep which   && \
            yum -y install gcc-gfortran gcc-c++  && \
            yum -y install openssl-devel.i686  glibc-devel.i686 libquadmath.i686 libgfortran.i686 libnsl2-devel.i686 blas-devel.i686 && \
            yum -y install libXau-devel.i686 libX11-devel.i686  lapack-devel.i686 xbae-devel.i686 libXaw-devel.i686 motif-devel.i686  && \
            yum -y install pythia8-devel.i686 pythia8.i686   && \
            yum -y install blas-devel.i686 && \
            dnf -y install HepMC3*.i686  --exclude=HepMC3*.x86_64 --exclude=root*.x86_64  --skip-broken && \
            dnf -y install root-*.i686 root-hbook.i686  liburing-devel.i686 --exclude=root*.x86_64 --skip-broken && \
            yum -y install https://kojipkgs.fedoraproject.org//packages/root/6.30.06/1.fc39/i686/root-hbook-6.30.06-1.fc39.i686.rpm --exclude=root*.x86_64  && \
            dnf -y install 'dnf-command(config-manager)'      && \
            dnf copr enable -y averbyts/HEPrpms  && \
            dnf -y install --skip-broken cernlib*.i686  && \
            yum -y clean all
