# Temporary Makefile for library interface. Generation date = Mon Oct 24 15:58:59 CEST 2016
include /home/andriish/Projects/JADE.git/trunk/jadesoft/GNUmake-rules
#
/home/andriish/Projects/JADE.git/trunk/jadesoft/lib/libinterface.a : /home/andriish/Projects/JADE.git/trunk/jadesoft/lib/libinterface.a( biby.o dlib.o plot10.o setcol.o ips.o igwlcm.o ranmar.o )
#
/home/andriish/Projects/JADE.git/trunk/jadesoft/lib/libinterface.a( plot10.o setcol.o igwlcm.o ) :\t cplot10.for
/home/andriish/Projects/JADE.git/trunk/jadesoft/lib/libinterface.a( plot10.o setcol.o ) :\t cpltcol.for
