name: 'Compile JADE'
description: 'JADE'
inputs:
  who-to-greet:  # id of input
    description: 'Set something'
    required: true
    default: 'Hi !'
outputs:
  time: # id of output
    description: 'Some result'
runs:
   uses: docker/login-action@v1.10.0
        with:
          registry: quay.io
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
