# Temporary Makefile for library source. Generation date = Mon Sep 22 07:48:20 CEST 2003
include /home/pcl2483/pedro/jadesoft/GNUmake-rules
#
/home/pcl2483/pedro/jadesoft/lib/libsource.a : /home/pcl2483/pedro/jadesoft/lib/libsource.a( lgcalb.o lganal9.o lgcdir9.o lginit.o lgerse.o lgmesg.o lgdcpy.o lgcctl.o lgclpb9.o lgclpc.o tpcnst.o lgrein.o ilctrc.o lgchc2.o intolg.o lgavdp.o lgthcr.o lgavde.o lgesmr.o lgecor9.o lgeerr.o lgbadc.o lgsubc.o lgclus.o lgcrnr.o lgeign.o lgbhit.o lgehit.o lgcrn2.o lgnmec.o englos.o posend.o enlosg.o angbar.o brlgn.o shmax.o lgsrth.o lgnbls.o lgbfil.o lgefil.o brlgn6.o elgobs.o bbleak.o lkcorr.o thcorr.o calcor.o encorr.o thcofa.o bbcorr.o lgbtdc.o lgdead.o )
#
/home/pcl2483/pedro/jadesoft/lib/libsource.a( lgcalb.o lganal9.o lgcdir9.o lgmesg.o lgdcpy.o lgclpb9.o tpcnst.o lgrein.o intolg.o lgecor9.o brlgn.o bbleak.o lkcorr.o thcorr.o encorr.o thcofa.o bbcorr.o lgbtdc.o ) :	 cdata.for
/home/pcl2483/pedro/jadesoft/lib/libsource.a( lgcalb.o lgerse.o lgbadc.o ) :	 clgkalb.for
/home/pcl2483/pedro/jadesoft/lib/libsource.a( lgcalb.o lganal9.o lgerse.o lgdcpy.o lgcctl.o lgclpb9.o lgclpc.o lgbadc.o lgclus.o lgeign.o lgsrth.o calcor.o ) :	 clgwork1.for
/home/pcl2483/pedro/jadesoft/lib/libsource.a( lgcdir9.o lgchc2.o intolg.o lgbfil.o lgefil.o ) :	 clgwork2.for
