# Temporary Makefile for library wertex. Generation date = Mon Sep 22 07:44:22 CEST 2003
include /home/pcl2483/pedro/jadesoft/GNUmake-rules
#
/home/pcl2483/pedro/jadesoft/lib/libwertex.a : /home/pcl2483/pedro/jadesoft/lib/libwertex.a( parkor.o wertex.o wtxaft.o wtxbnk.o wtxee.o wtxeer.o wtxerr.o wtxini.o wtxpnt.o wtxpre.o wtxsrc.o wtxcrv.o xfwid.o xfwvxc.o )
#
/home/pcl2483/pedro/jadesoft/lib/libwertex.a( xfwid.o xfwvxc.o ) :	 cadmin.for
/home/pcl2483/pedro/jadesoft/lib/libwertex.a( parkor.o wtxbnk.o wtxeer.o wtxpre.o xfwid.o xfwvxc.o ) :	 cdata.for
