# Temporary Makefile for library tagg. Generation date = Mon Sep 22 07:49:21 CEST 2003
include /home/pcl2483/pedro/jadesoft/GNUmake-rules
#
/home/pcl2483/pedro/jadesoft/lib/libtagg.a : /home/pcl2483/pedro/jadesoft/lib/libtagg.a( tagan.o tagint.o anatag.o amctag.o tagadc.o tagped.o tagkal.o tagpd1.o tagpd2.o repack.o tracks.o tagraw.o tagh2s.o taggtp.o tagpos.o tagsum.o tagsr1.o tagsr2.o tagdir.o tagcol.o tagsto.o tagps1.o tagps2.o tagcls.o tagfit.o tagphi.o tagfty.o tagrty.o tagmrk.o tagchk.o tagneb.o ggsort.o ggcctl.o ggclpc.o ggfac2.o ggclus.o ggresq.o ggsrth.o conver.o lumons.o sort.o umcpak.o rcoord.o gscrub.o tags2h.o )
#
/home/pcl2483/pedro/jadesoft/lib/libtagg.a( tagkal.o ) :	 calibr.for
/home/pcl2483/pedro/jadesoft/lib/libtagg.a( tagan.o tagadc.o tagkal.o tagraw.o tagh2s.o taggtp.o tagmrk.o tagchk.o ) :	 cdata.for
/home/pcl2483/pedro/jadesoft/lib/libtagg.a( tagint.o tagadc.o tagraw.o tagsum.o tagmrk.o ) :	 cgraph.for
/home/pcl2483/pedro/jadesoft/lib/libtagg.a( tagan.o tagint.o tagadc.o taggtp.o tagsr2.o tagps1.o tagcls.o tagfit.o tagneb.o ) :	 comtag.for
/home/pcl2483/pedro/jadesoft/lib/libtagg.a( tagan.o taggtp.o tagcol.o ) :	 ctaggo.for
/home/pcl2483/pedro/jadesoft/lib/libtagg.a( tags2h.o tagan.o tagint.o anatag.o tagadc.o tagped.o tagkal.o tagpd1.o tagpd2.o tagraw.o tagh2s.o taggtp.o tagpos.o tagsum.o tagsr1.o tagsr2.o tagps1.o tagcls.o tagfit.o tagmrk.o tagchk.o tags2h.o ) :	 cwktag.for
