# Temporary Makefile for library patrecsr. Generation date = Mon Sep 22 07:47:21 CEST 2003
include /home/pcl2483/pedro/jadesoft/GNUmake-rules
#
/home/pcl2483/pedro/jadesoft/lib/libpatrecsr.a : /home/pcl2483/pedro/jadesoft/lib/libpatrecsr.a( inpatr.o inpatc.o patrec.o adpatr.o patrc1.o srtrel.o backtr.o prhtar.o flinel.o bstore.o bside.o rincon.o bakfit.o fxyz.o xyfit.o errorm.o pcwork.o kntrel.o ftrkel.o bakpak.o patrol.o zrfit.o deadcl.o trlord.o rstbtr.o crtrel.o )
#
/home/pcl2483/pedro/jadesoft/lib/libpatrecsr.a( fxyz.o patrol.o ) :	 calibr.for
/home/pcl2483/pedro/jadesoft/lib/libpatrecsr.a( patrc1.o srtrel.o prhtar.o fxyz.o kntrel.o patrol.o rstbtr.o crtrel.o ) :	 ccycp.for
/home/pcl2483/pedro/jadesoft/lib/libpatrecsr.a( inpatc.o patrec.o patrc1.o srtrel.o prhtar.o fxyz.o pcwork.o kntrel.o bakpak.o rstbtr.o crtrel.o ) :	 cdata.for
/home/pcl2483/pedro/jadesoft/lib/libpatrecsr.a( patrol.o ) :	 cdatamin.for
/home/pcl2483/pedro/jadesoft/lib/libpatrecsr.a( inpatc.o backtr.o bstore.o bside.o rincon.o fxyz.o ftrkel.o patrol.o ) :	 cdsmax.for
/home/pcl2483/pedro/jadesoft/lib/libpatrecsr.a( inpatr.o zrfit.o ) :	 cgraph.for
/home/pcl2483/pedro/jadesoft/lib/libpatrecsr.a( patrc1.o zrfit.o ) :	 cheadr.for
/home/pcl2483/pedro/jadesoft/lib/libpatrecsr.a( inpatc.o backtr.o prhtar.o bstore.o bside.o rincon.o ftrkel.o zrfit.o rstbtr.o ) :	 cjdrch.for
/home/pcl2483/pedro/jadesoft/lib/libpatrecsr.a( backtr.o ) :	 clbpgm.for
/home/pcl2483/pedro/jadesoft/lib/libpatrecsr.a( inpatr.o adpatr.o patrc1.o srtrel.o backtr.o flinel.o bstore.o bside.o rincon.o bakfit.o fxyz.o xyfit.o errorm.o kntrel.o ftrkel.o bakpak.o patrol.o zrfit.o ) :	 cpatlm.for
/home/pcl2483/pedro/jadesoft/lib/libpatrecsr.a( patrec.o patrc1.o srtrel.o prhtar.o flinel.o bakfit.o fxyz.o xyfit.o pcwork.o kntrel.o ftrkel.o bakpak.o patrol.o zrfit.o rstbtr.o crtrel.o ) :	 cworkeq.for
/home/pcl2483/pedro/jadesoft/lib/libpatrecsr.a( backtr.o bstore.o bside.o rincon.o ) :	 cworkmx.for
/home/pcl2483/pedro/jadesoft/lib/libpatrecsr.a( patrec.o patrc1.o srtrel.o backtr.o prhtar.o flinel.o bstore.o bside.o rincon.o bakfit.o fxyz.o xyfit.o pcwork.o kntrel.o ftrkel.o bakpak.o patrol.o zrfit.o trlord.o rstbtr.o crtrel.o ) :	 cworkpr.for
/home/pcl2483/pedro/jadesoft/lib/libpatrecsr.a( xyfit.o ) :	 cxyfit.for
