# Temporary Makefile for library jmc. Generation date = Mon Sep 22 07:45:46 CEST 2003
include /home/pcl2483/pedro/jadesoft/GNUmake-rules
#
/home/pcl2483/pedro/jadesoft/lib/libjmc.a : /home/pcl2483/pedro/jadesoft/lib/libjmc.a( mcnews.o muconm.o jinit.o evtini.o jgetev.o jgetvc.o mctagm.o trcdet.o trcdtv.o trcoil.o jtrkgm.o jtrntr.o trlgl.o murtne.o jstore.o jspoin.o ordlg.o muordr.o tofmak.o wrtmcb.o mcvsum.o inifwd.o inttof.o mctagi.o brvect.o mctagc.o mctage.o pikmuf.o jprfre.o jprabs.o jprtlo.o jipatr.o jchamb.o jprthi.o trkadc.o svect1.o jhitin.o jvtxch.o endclg.o trkgmv.o trkgam.o trlgsh.o trlgs6.o plligd.o hdecls.o showr.o sthead.o stlatc.o statbp.o stalgn.o statag.o mchist.o mcvali.o stvect.o stpall.o mctagb.o mctagf.o jstep.o setbpc.o settof.o actof.o jmulsc.o jeloss.o jtrapz.o jring.o jftest.o jvdtim.o eepair.o wegas.o limint.o errmsg.o rnexp0.o rncont.o rngau.o fcrang.o datemc.o tags2h.o mctagr.o mctags.o mcverr.o rtmi.o radiat.o jrchck.o jdtime.o )
#
/home/pcl2483/pedro/jadesoft/lib/libjmc.a( trlgsh.o trlgs6.o limint.o ) :	 cgeo1.for
/home/pcl2483/pedro/jadesoft/lib/libjmc.a( errmsg.o ) :	 cheadr.for
/home/pcl2483/pedro/jadesoft/lib/libjmc.a( mctagm.o mctagi.o statag.o mctagr.o mctags.o ) :	 cmctag.for
/home/pcl2483/pedro/jadesoft/lib/libjmc.a( brvect.o mcvali.o stvect.o stpall.o ) :	 cprod.for
/home/pcl2483/pedro/jadesoft/lib/libjmc.a( tags2h.o ) :	 cwktag.for
