C   29/06/79 705041254  MEMBER NAME  MOMENP   (JADEGS)      FORTRAN
      SUBROUTINE MOMENP(IP,PX,PY,PZ,PTRANS,PTOT,PHI,THE)
      IMPLICIT INTEGER*2 (H)
C---
C---  NOTE:  MOMENP IS IDENTICAL TO MOMENT, OF WHICH IT IS A COPY, ONCE
C---         MADE BY HEINZELMANN. BECKER COPIED IT BACK FROM HEINZELMANN
C---         IT IS USED BY DEDXBN          J.O.
C---
C---     GIVEN:  POINTER TO TRACK BANK IP
C---     RETURN: THREE COMPONENTS OF THE MOMENTUM
C---          J.OLSSON  29.06.79        LAST CHANGE  04.05.87
C---                                    COPIED FROM F11HEI   (LB)
#include "cdata.for"
#include "cgraph.for"
      COMMON /CJTRIG/ PI,TWOPI
      DATA VELH /.2998E-4/
C----------------------------------------
      IPHEAD=IDATA(IBLN('HEAD'))
      IHHEAD=IPHEAD*2
      VELHB = ABS(VELH*.001*HDATA(IHHEAD+30))
C
      PZ = 0.
      PTRANS = 0.
      RAD = ADATA(IP+25)
      RAD = ABS(RAD)
      IF(RAD.LT.1.E-09) GO TO 7300
      PTRANS = VELHB/RAD
7300  CONTINUE
C  PLONG AND PTOT COMPUTED FROM STRAIGHT LINE FIT INVOLVING Z
C     IF(IDATA(IP+29).NE.1) GO TO 7301
C  Z-R FIT
C    NOTE: THE CORRECT FITTING IS ALWAYS A Z-S FIT, THE Z-R FIT IS ONLY
C    AN APPROXIMATION, VALID AT HIGH MOMENTA FOR TRACKS IN RADIAL FLIGHT
C    DIRECTION (I.E., NOT FOR V0 TRACKS!). TYPE 2 CORRESPONDS TO SPITZER
C    HELIX-FIT, 'THE' FROM THE PARAMETER P1 (DR/DZ OR DR/DS) IS THE SAME
C    (FORMALLY) AS IN THE OLD Z-R FIT CASE.
C
C  Z-R FIT
      THE = ATAN(ADATA(IP+30))
      PTOT = PTRANS/COS(THE)
      PZ = SQRT(PTOT*PTOT - PTRANS*PTRANS)
      IF(THE.LT.0.) PZ = - PZ
      THE = PI*.5 - THE
      GO TO 7302
C  Z-FI FIT  (FI IS HELIX ROTATION ANGLE)
C7301  IF(IDATA(IP+29).NE.2) GO TO 7302
C      PZ = VELHB*ADATA(IP + 30)
7302  THE = ACOS(ADATA(IP+10))
      PFIX = ADATA(IP+8)
      PFIY = ADATA(IP+9)
      IF(PFIX.NE.0..OR.PFIY.NE.0.) GO TO 3633
      WRITE(6,3367) HDATA(IHHEAD+10),HDATA(IHHEAD+11)
3367  FORMAT(' MOMENT ### WARNING ##  RUN EV.',2I8,' WITH 0,0 DIR.COSINE
     $S !!')
      PHI = 0.
      GO TO 3670
3633  PHI = ATAN2(ADATA(IP+9),ADATA(IP+8))
      IF(PHI.LT.0.) PHI = PHI + TWOPI
3670  PX = PTRANS * COS(PHI)
      PY = PTRANS * SIN(PHI)
      PTOT = SQRT(PTRANS*PTRANS + PZ*PZ + .00000000001)
      RETURN
      END
