/********************************************************************
* Frame_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Frame_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
    extern void G__cpp_setup_tagtableFrame_Dict();
    extern void G__cpp_setup_inheritanceFrame_Dict();
    extern void G__cpp_setup_typetableFrame_Dict();
    extern void G__cpp_setup_memvarFrame_Dict();
    extern void G__cpp_setup_globalFrame_Dict();
    extern void G__cpp_setup_memfuncFrame_Dict();
    extern void G__cpp_setup_funcFrame_Dict();
    extern void G__set_cpp_environmentFrame_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Frame.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Frame_DictLN_TClass;
extern G__linked_taginfo G__Frame_DictLN_TBuffer;
extern G__linked_taginfo G__Frame_DictLN_TMemberInspector;
extern G__linked_taginfo G__Frame_DictLN_TObject;
extern G__linked_taginfo G__Frame_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Frame_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Frame_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Frame_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Frame_DictLN_TGObject;
extern G__linked_taginfo G__Frame_DictLN_TQObject;
extern G__linked_taginfo G__Frame_DictLN_TGWindow;
extern G__linked_taginfo G__Frame_DictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__Frame_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__Frame_DictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Frame_DictLN_TGFrame;
extern G__linked_taginfo G__Frame_DictLN_TGCompositeFrame;
extern G__linked_taginfo G__Frame_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__Frame_DictLN_TGMainFrame;
extern G__linked_taginfo G__Frame_DictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__Frame_DictLN_Frame;

/* STUB derived class for protected member access */
