C   25/06/78 708272231  MEMBER NAME  ENELEL   (S)           FORTRAN
      FUNCTION ENELEL(E)
C
C THIS FUNCTION GIVES THE AVERAGE IONIZATION LOSS, I.E. ENERGY LOSS
C FOR ELECTRONS.
C THIS IS FORMULA (13) IN UEHLING, ANN.REV.NUCL.PHYS. 4 (1954)315
C
C  NOTE THAT THE INPUT ENERGY COMES IN UNITS OF ME, I.E. == GAMMA,
C  THEREFORE     BETA**2 = 1 - 1/E**2
C  LN2 = .69315
C
C  COMMON/ILPAR/ IS SET IN PARST2, CALLED BY INTSHW
C
      COMMON/ILPAR/AI,BI,ALCUTM
      DATA RME/0.511/
C
      BE2=1.-1./E**2
      IF(BE2.LE.0.)GOTO10
      EKIN = (E-1.)*RME
C
      CON=ALOG(E)+ALOG(BE2)/2.
C
      BIPRIM = BI - .69315
C
      ENELEL=AI*(BIPRIM + ALOG(BE2) - ALOG(1.-BE2) + ALOG(EKIN)
     @ + (1.-BE2) - .69315*(2.*E-1.)/E**2
     @ + 0.125*((E-1.)/E)**2
     @         -DENDEL(0.434294*CON))/BE2
C FUNCTION DENDEL CALCULATES DENSITY EFFECT CORRECTION.
      RETURN
 10   ENELEL=0.
      RETURN
      END
