# Temporary Makefile for library interface. Generation date = Mon Sep 22 07:35:19 CEST 2003
include /home/pcl2483/pedro/jadesoft/GNUmake-rules
#
/home/pcl2483/pedro/jadesoft/lib/libinterface.a : /home/pcl2483/pedro/jadesoft/lib/libinterface.a( biby.o dlib.o plot10.o setcol.o ips.o igwlcm.o ranmar.o )
#
/home/pcl2483/pedro/jadesoft/lib/libinterface.a( plot10.o setcol.o igwlcm.o ) :	 cplot10.for
/home/pcl2483/pedro/jadesoft/lib/libinterface.a( plot10.o setcol.o ) :	 cpltcol.for
