# Temporary Makefile for library interface. Generation date = Sun Oct 23 16:52:05 CEST 2016
include /home/andriish/Projects/JADE.git/trunk/jadesoft/GNUmake-rules
#
/home/andriish/Projects/JADE.git/trunk/jadesoft/lib/libinterface.a : /home/andriish/Projects/JADE.git/trunk/jadesoft/lib/libinterface.a( biby.o dlib.o plot10.o setcol.o ips.o igwlcm.o ranmar.o )
#
/home/andriish/Projects/JADE.git/trunk/jadesoft/lib/libinterface.a( plot10.o setcol.o igwlcm.o ) :	 cplot10.for
/home/andriish/Projects/JADE.git/trunk/jadesoft/lib/libinterface.a( plot10.o setcol.o ) :	 cpltcol.for
