name: build
on:
 push:
 pull_request:
 schedule:
#Every 50 days at midnight 
    - cron:  "0 0 1/600 * *"

jobs:
  Fedora39x86_64_GNU:
    name: Fedora39x86_64_GNU
    runs-on: ubuntu-latest
    container:
        image: fedora:39
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install 
      run: |
            yum -y  install  dnf-plugins-core 
            yum -y  install            bc make ninja-build cmake binutils git wget diffutils file sed gawk grep which  
            yum -y  install            gcc-gfortran gcc-c++ openssl-devel openssl 
            yum -y  install            openssl-devel.i686  glibc-devel.i686 libquadmath.i686 libgfortran.i686 libnsl2-devel.i686
            yum -y  install            openssl-devel.i686  blas.i686 blas-devel.i686
            yum -y  install            libXau.i686 libX11.i686  lapack-devel.i686 lapack.i686 
            yum -y  install            xbae.i686 xbae-devel.i686 libXaw-devel.i686 libXaw.i686 
            yum -y  install            motif-devel.i686 motif.i686 
            yum -y  install            pythia8-devel.i686 pythia8.i686  
            dnf -y install --skip-broken HepMC3*.i686  --exclude=HepMC3*.x86_64 --exclude=root*.x86_64
            dnf -y install --skip-broken root-*.i686   --exclude=root*.x86_64
            dnf -y install  'dnf-command(config-manager)'     
            dnf copr enable -y averbyts/HEPrpms
            dnf -y install --skip-broken cernlib*.i686
            yum -y clean all

    - name: Compile
      run: |
           sh jadeinstall.sh --bits=32
           sh jadetest.sh --bits=32
