name: build
on:
 push:
 pull_request:
 schedule:
#Every 50 days at midnight 
    - cron:  "0 0 1/600 * *"

jobs:
  Fedora39x86_64_GNU:
    name: Fedora39x86_64_GNU
    runs-on: ubuntu-latest
    container:
        image: fedora:39
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install 
      run: |
            yum -y install dnf-plugins-core 
            yum -y install bc make ninja-build cmake binutils git wget diffutils file sed gawk grep which  
            yum -y install gcc-gfortran gcc-c++ 
            yum -y install openssl-devel.i686  glibc-devel.i686 libquadmath.i686 libgfortran.i686 libnsl2-devel.i686 blas-devel.i686
            yum -y install libXau-devel.i686 libX11-devel.i686  lapack-devel.i686 xbae-devel.i686 libXaw-devel.i686 motif-devel.i686 
            yum -y install pythia8-devel.i686 pythia8.i686  
            dnf -y install HepMC3*.i686  --exclude=HepMC3*.x86_64 --exclude=root*.x86_64  --skip-broken
            dnf -y install root-*.i686 root-hbook.i686  liburing-devel.i686 --exclude=root*.x86_64 --skip-broken
            yum -y install https://kojipkgs.fedoraproject.org//packages/root/6.30.02/3.fc39/i686/root-hbook-6.30.02-3.fc39.i686.rpm --exclude=root*.x86_64
            dnf -y install 'dnf-command(config-manager)'     
            dnf copr enable -y averbyts/HEPrpms
            dnf -y install --skip-broken cernlib*.i686
            yum -y clean all

    - name: Compile
      run: |
           sh jadeinstall.sh --bits=32
           sh jadetest.sh --bits=32

  build-JADE-docker-image:
    runs-on: ubuntu-latest
    name: Build JADE Docker image
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 2 
    - name: Check if the Docker file was changed
      id: changed-docker-files
      uses: tj-actions/changed-files@v38
      with:
          files: Dockerfile

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the JADE Docker image on the change of Dockerfile
      if: steps.changed-docker-files.outputs.any_changed == 'true' 
      run: |
         docker build . --tag ghcr.io/andriish/jade:latest
         docker run ghcr.io/andriish/jade:latest
         docker push ghcr.io/andriish/jade
    - name: Build the JADE Docker image on schedule
      if: ${{ github.event_name == 'schedule' }}
      run: |
         docker build . --tag ghcr.io/andriish/jade:latest
         docker run ghcr.io/andriish/jade:latest
         docker push ghcr.io/andriish/jade