name: build
on:
 push:
 pull_request:
 schedule:
#Every 50 days at midnight 
    - cron:  "0 0 1/600 * *"

env:
  REGISTRY_URL: quay.io

jobs:
  #compilejobCentOS7:
    #if: "!contains(github.event.head_commit.message, 'skip ci')"
    #runs-on: ubuntu-latest
    #name: JADE_on_CentOS7
    #steps:
    #- name: Checkout
      #uses: actions/checkout@v2
    #- name: Compile
      #id: compileindocker
      #uses: ./.github/workflows/centos7
    #- name: Get the output status
      #run: exit ${{ steps.compileindocker.outputs.out }}

  #compilejobCentOS8:
    #if: "!contains(github.event.head_commit.message, 'skip ci')"
    #runs-on: ubuntu-latest
    #name: JADE_on_CentOS8
    #steps:
    #- name: Checkout
      #uses: actions/checkout@v2
    #- name: Compile
      #id: compileindocker
      #uses: ./.github/workflows/centos8
      #with:
          #registry: quay.io
    #- name: Get the output status
      #run: exit ${{ steps.compileindocker.outputs.out }}

  compilejobCentOS9:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    name: JADE_on_CentOS9stream
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Quay.io
      uses: docker/login-action@v1
      with:
          registry: quay.io
    - name: Compile
      id: compileindocker
      uses: ./.github/workflows/centos9
    - name: Get the output status
      run: exit ${{ steps.compileindocker.outputs.out }}

      
  #compilejobOSX:
    #if: "!contains(github.event.head_commit.message, 'skip ci')"
    #runs-on: macos-latest
    #name: JADE_on_OSX
    #steps:
    #- name: Checkout
      #uses: actions/checkout@v2
    #- name: Compile
      #id: compile
      #run: ./.github/workflows/osx/entrypoint.sh
