name: build
on:
 push:
 pull_request:
 schedule:
#Every 50 days at midnight 
    - cron:  "0 0 1/600 * *"

jobs:
  compilejobCentOS7:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    name: JADE_on_CentOS7
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile
      id: compileindocker
      uses: ./.github/workflows/centos7
    - name: Get the output status
      run: exit ${{ steps.compileindocker.outputs.out }}

  compilejobCentOS8:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    name: JADE_on_CentOS8
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile
      id: compileindocker
      uses: ./.github/workflows/centos8
    - name: Get the output status
      run: exit ${{ steps.compileindocker.outputs.out }}
      
  compilejobOSX:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: macos-latest
    name: JADE_on_OSX
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile
      id: compile
      run: ./.github/workflows/osx/entrypoint.sh
