# Temporary Makefile for library zlib. Generation date = Mon Sep 22 07:50:48 CEST 2003
include /home/pcl2483/pedro/jadesoft/GNUmake-rules
#
/home/pcl2483/pedro/jadesoft/lib/libzlib.a : /home/pcl2483/pedro/jadesoft/lib/libzlib.a( ze4vpk.o fehler.o zmcredu.o ze4vtp.o irnevt.o prtoci.o ze4vvx.o crdoca.o ze4vmc.o eamcde.o ze4vea.o ze4vun.o ze4vdp.o jobfin.o ze4vet.o ekand.o prlist.o dxmcgn.o eazero.o ealgcl.o eaunin.o chien5.o prallb.o trkbl9.o trkbse.o shado9.o shwcpr.o prsinb.o expect.o zspthak.o zsphrcy.o )
#
/home/pcl2483/pedro/jadesoft/lib/libzlib.a( ze4vvx.o ) :	 calibr.for
/home/pcl2483/pedro/jadesoft/lib/libzlib.a( chien5.o trkbl9.o trkbse.o shado9.o ) :	 cdata.for
/home/pcl2483/pedro/jadesoft/lib/libzlib.a( ealgcl.o chien5.o trkbl9.o trkbse.o shado9.o expect.o ) :	 cgeo1.for
